### PR TITLE
[Fixes #25][Fixes #27][Fixes #28][Fixes #29][Fixes #30][Fixes #31] Several type handling fixes

### LINKED ISSUE #25: Primitive types not supported when specified with metadata
When trying to process an ADOC with "bytes" type following error is raised

```
	Traceback (most recent call last):
	  File "/home/fer/.local/bin/avro-to-python", line 8, in <module>
		sys.exit(main())
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 956, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 555, in invoke
		return callback(*args, **kwargs)
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/cli.py", line 33, in main
		reader.read()
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/reader/read.py", line 81, in read
		self._build_namespace_tree()
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/reader/read.py", line 163, in _build_namespace_tree
		_record_file(file, item, queue)
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/files/record.py", line 80, in _record_file
		field = _union_field(
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/types/union.py", line 58, in _union_field
		field_type = _get_field_type(
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/types/type_factory.py", line 49, in _get_field_type
		raise ValueError(
	ValueError: bytes is not supported.

```

### LINKED ISSUE #27: Multidimensional arrays are not supported
Consider following schema:

```
{
  "type" : "record",
  "name" : "RecordWithMultiDimensionalArray",
  "namespace" : "test",
  "fields" : [ {
    "name" : "coordinates",
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "array",
        "items" : "double",
        "java-class" : "[D"
      },
      "java-class" : "[[D"
    }
  } ]
}
```
It fails with following error when trying to be processed:

```
Traceback (most recent call last):
  File "/home/fer/.local/bin/avro-to-python", line 8, in <module>
    sys.exit(main())
  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/cli.py", line 34, in main
    reader.read()
  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/reader/read.py", line 81, in read
    self._build_namespace_tree()
  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/reader/read.py", line 164, in _build_namespace_tree
    _record_file(file, item, queue)
  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/files/record.py", line 45, in _record_file
    field = _array_field(
  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/types/array.py", line 93, in _array_field
    f"avro type {field['items']['type']} is not supported"
KeyError: 'items'
```

### LINKED ISSUE #28: Serialization to JSON of `bytes` fails
When trying to serialize to JSON an object generated from an schema with a `bytes` type it fails with following error:

```
Traceback (most recent call last):
  File "O:\ws\mdp\avro-to-python\mytest.py", line 13, in <module>
    print(f"Hello CDM. This is my first entity: {myEvent.serialize()}")
  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\mdh_model_common\com\kapschtraffic\mdp\mdh\model\common\events\BaseEvent.py", line 259, in serialize
    return json.dumps(self, default=default_json_serialize)
  File "C:\Users\miguelez\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\miguelez\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\miguelez\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\mdh_model_common\helpers.py", line 11, in default_json_serialize
    return obj.__dict__
AttributeError: 'bytes' object has no attribute '__dict__'. Did you mean: '__dir__'?

Process finished with exit code 1
```

### LINKED ISSUE #29: Allow generated objects to be instantiated without a JSON, dict or object copy
Generated constructor requires either a `JSON` string, a dictionary or another instance of the same object. 

This way it is not possible to initialize an object and fill it up just using the setters. 

Using a dict has also disadvantages as error checking is delayed to runtime.

### LINKED ISSUE #30: Support union as array item type
Defining an array with an item of type "union" is not supported and raises following error:

```
	Traceback (most recent call last):
	  File "/usr/local/bin/avro-to-python", line 8, in <module>
		sys.exit(main())
	  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
		rv = self.invoke(ctx)
	  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
		return __callback(*args, **kwargs)
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/cli.py", line 34, in main
		reader.read()
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/reader/read.py", line 81, in read
		self._build_namespace_tree()
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/reader/read.py", line 164, in _build_namespace_tree
		_record_file(file, item, queue)
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/utils/avro/files/record.py", line 80, in _record_file
		field = _union_field(
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/utils/avro/types/union.py", line 80, in _union_field
		kwargs['union_types'].append(_array_field(field={'name': 'arraytype', 'type': typ}, parent_namespace=parent_namespace, queue=queue, references=references))
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/utils/avro/types/array.py", line 50, in _array_field
		field_item_type = _get_field_type(
	  File "/usr/local/lib/python3.9/site-packages/avro_to_python/utils/avro/types/type_factory.py", line 22, in _get_field_type
		if isinstance(field['type'], dict):
	TypeError: list indices must be integers or slices, not str
	EXIT on build_script with code 1
```

This is an example of AVSC that triggers the error:

```
{
    "type": "record",
    "name": "RecordWithArrayOfUnion",
    "namespace": "records",
    "fields": [
        {
            "name": "arrayOfUnion",
            "type": {
                "type": "array",
                "items": [
                    {
                        "type": "array",
                        "items": {
                            "type": "Thing"
                        }
                    },
                    "int"
                ]
            }
        }
    ]
}
```

### LINKED ISSUE #31: Encoding selection not supported
When trying to process avsc encoded as UTF-8 in windows following error is thrown (if non-ascii characters are present):

```
	Traceback (most recent call last):
	  File "O:\ws\mdp\avro-to-python\venv\Scripts\avro-to-python-script.py", line 33, in <module>
		sys.exit(load_entry_point('avro-to-python', 'console_scripts', 'avro-to-python')())
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\click\core.py", line 1128, in __call__
		return self.main(*args, **kwargs)
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\click\core.py", line 1053, in main
		rv = self.invoke(ctx)
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\click\core.py", line 1395, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\click\core.py", line 754, in invoke
		return __callback(*args, **kwargs)
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\avro_to_python\cli.py", line 34, in main
		reader.read()
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\avro_to_python\reader\read.py", line 80, in read
		self._read_files()
	  File "O:\ws\mdp\avro-to-python\venv\lib\site-packages\avro_to_python\reader\read.py", line 125, in _read_files
		serialized = json.load(f)
	  File "C:\Users\miguelez\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
		return loads(fp.read(),
	  File "C:\Users\miguelez\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
		return codecs.charmap_decode(input,self.errors,decoding_table)[0]
	UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 41600: character maps to <undefined>
```

### PR DESCRIPTION
**Pull request by fmiguelez**
* Fixes #25
* Fixes #27
* Fixes #28
* Fixes #29
* Fixes #30
* Fixes #31

### CODE REVIEW

**Comment by fmiguelez** [comment]
@SRserves85 could you please review this PR?

**Comment by fmiguelez** [comment]
@perj @balexander @RZachLamberty @chasdevs @jkleung11 
Could anyone review this PR @SRserves85 seems to be gone?

I would not like to open another unnecessary fork as this library has proven really useful.

**Comment by perj** [comment]
Sorry, I don't have write access to this repo.

**Comment by fmiguelez** [comment]
Thanks @SRserves85. When do you think a new version of the library can be released?

**Pull request merged**
